# escape=`
FROM microsoft/windowsservercore:1709
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco install jdk8 --version 8.0.152 -y; `
    choco install groovy  --version 2.4.13 -y; `
    refreshenv; `
    [Environment]::SetEnvironmentVariable("\"JAVA_HOME\"", "\"C:\Program Files\Java\jdk1.8.0_152\"", "\"Machine\""); `
    [Environment]::SetEnvironmentVariable("\"path\"", "\"$($env:path);C:\tools\groovy-2.4.13\bin\"", "\"Machine\"");